# Generated by Django 3.2.4 on 2021-08-20 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0005_auto_20210818_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
